.file0.assetId: {AssetId: d41d19d7-fef9-4034-a3e3-6589d657d863}
.file0.files: {Var: 1}

.file1!script: {Var: EditorSettings}
.file1!scriptId: {AssetId: 3dfd7ca5-2750-4783-b7ef-9fced505568d}
.file1.StartupScene.assetId: {AssetId: 7a58f68f-8c33-409c-ae07-eb60cb9e512c}

